from typing import Dict
import matplotlib.pyplot as plt

LABEL_MAP: Dict[str, str] = {
    "BDT_score": "BDT score",
    "NNScore": "NN score",
    "mlp_score": "NN Score",
    "NNScore_OOF": r"$NN_{\text{hadhad}} \text{ score}$",
    "metres_njet": r"$p_T^{miss}$ resolution [MMC]",
    "aplanarity": r"Aplanarity",

    "sphericity": r"Sphericity",
    "thrust": r"Thrust",
    "pT_B_had_1": r"Truth leading B-hadron $p_{\text{T}}$ [GeV]",
    "pT_B_had_2": r"Truth sub-leading B-hadron $p_{\text{T}}$ [GeV]",
    "pT_B_had_3": r"Truth third leading B-hadron $p_{\text{T}}$ [GeV]",
    "pT_B_had_4": r"Truth fourth leading B-hadron $p_{\text{T}}$ [GeV]",
    "pT_visible_tauhad_1": r"Truth leading hadronic tau $p_{\text{T}}$ [GeV]",
    "pT_visible_tauhad_2": r"Truth sub-leading hadronic tau $p_{\text{T}}$ [GeV]",

    "xwt": r"$X_{Wt}$",
    "mTb_min": r"$m^T_{b,min}$ [GeV]",
    "metsig_est": r"$S_{\text{est}}(p_T^{miss})$",
    "metsig_derived": r"$S_{\text{obj}}(p_T^{miss})$",
    "RMS_mjj": r"RMS$(m_{bb})$",
    "RMS_dEta": r"RMS$(\Delta\eta(bb))$",
    "RMS_dR": r"RMS$(\Delta R(bb))$",
    "m_h1_absmass": r"$m_{H_1}^{\text{abs}}$ [GeV]",
    "m_h1_squaremass": r"$m_{H_1}^{\text{square}}$ [GeV]",
    "m_h1_absmass_massordered": r"Mass-ordered $m_{H_1}^{\text{abs}}$[GeV]",
    "m_h1_squaremass_massordered": r"Mass-ordered $m_{H_1}^{\text{square}}$[GeV]",
    "m_h1_random":  r"$m_{H_1}^{\text{rand}}$ [GeV]",
    "m_h2_random":  r"$m_{H_2}^{\text{rand}}$ [GeV]",
    "m_h1_LR": r"$m_{H_1}$ [GeV] (LR)",
    "m_h2_absmass": r"$m_{H_2}^{\text{abs}}$ [GeV]",
    "m_h2_absmass_massordered": r"Mass-ordered $m_{H_2}^{\text{abs}}$[GeV]",
    "m_h2_squaremass_massordered": r"Mass-ordered $m_{H_2}^{\text{square}}$[GeV]",
    "m_h2_LR": r"$m_{H_2}$ [GeV] (LR)",
    "m_h1": r"$m_{H_1}^{\Delta R}$ [GeV]",
    "m_h2": r"$m_{H_2}^{\Delta R}$ [GeV]",
    "m_h1_recomatch": r"Reco-matched $m_{H_1}$ [GeV]",
    "m_h2_recomatch": r"Reco-matched $m_{H_2}$ [GeV]",
    "m_Htautau_reco": r"Reco-matched $m_{\tau\tau}^{\text{vis}}$ [GeV]",
    "m_Htautau_MC": r"Truth $m_{\tau\tau}^{\text{vis}}$ [GeV]",
    "asym_x_y": r"$\sigma(p_{\text{x}}^{\text{miss}}) - \sigma(p_{\text{y}}^{\text{miss}})$",    
    "m_h2_squaremass": r"$m_{H_2}^{\text{square}}$ [GeV]",
    "dm_h1_absmassdR": r"$\Delta m_{H_1}($abs-mass, $\Delta R)$ [GeV]",
    "dm_h2_absmassdR": r"$\Delta m_{H_2}($abs-mass, $\Delta R)$ [GeV]",
    "m_tautau_col": r"$m_{\tau\tau}^{\text{col}}$ [GeV]",
    "m_tautau_mT": r"$m_{\tau\tau}^{\text{T}}$ [GeV]",
    "m_tautau_smin": r"$s_{min}$ [GeV]",
    "m_tautau_vis": r"$m_{\tau\tau}^{vis}$ [GeV]",
    "m_tautau_vis_OS": r"$m_{\tau\tau}^{vis-OS}$ [GeV]",
    "m_tautau_vis_OS_nob": r"$m_{\tau\tau}^{vis-OS}$ (OR) [GeV]",
    "mtautau_new": r"$m_{\tau\tau}^{col | T}$ [GeV]",
    "dR_H1H2": r"$\Delta R(H_1, H_2)$",
    "dR_H1Htau": r"$\Delta R(H_1, H_{\tau})$",
    "dR_H2Htau": r"$\Delta R(H_2, H_{\tau})$",
    #"dPhi_met_tautau":  r"$\Delta \phi(p_T(H_{\tau\tau}), E_T^{miss})$",
    "dPhi_H1H2": r"$\Delta \phi(H_1, H_2)$",
    "dPhi_H1Htau": r"$\Delta \phi(H_1, H_{\tau})$",
    "dPhi_H2Htau": r"$\Delta \phi(H_2, H_{\tau})$",
    "dphi_truth_vismis_1": r"$\Delta \phi(p(\text{visible}), p(\text{missing}))$",
    "dphi_truth_vismis_2": r"$\Delta \phi(p(\text{visible}), p(\text{missing}))$",
    "MH_MMC_mass": r"$m_{\tau\tau}^{\text{MMC}}$ [MH]",
    "MMC_mass_lepHad": r"$m_{\tau\tau}^{\text{MMC}}$ [LH]",
    "MMC_mass_lepHad_rescan": r"$m_{\tau\tau}^{\text{MMC}}$ [LH]",

    "dEta_H1H2": r"$\Delta \eta(H_1, H_2)$",
    "dEta_H1Htau": r"$\Delta \eta(H_1, H_{\tau})$",
    "dEta_H2Htau": r"$\Delta \eta(H_2, H_{\tau})$",
    "m_tautau_col_truthmatch": r"$m_{\tau\tau}^{col-truth}$ [GeV]",
    "MMC_mass_metscan": r"$m_{\tau\tau}^{MMC}$ ($p_T^{\text{miss}},\phi$-scan) [GeV]",
    "MMC_mass": r"$m_{\tau\tau}^{MMC}$ ($\phi$-scan) [GeV]",
    "MH_MMC_mass_sat": r"$m_{\tau\tau}^{MMC}$ [GeV]",
    "mmc_peak": r"$m_{\tau\tau}^{MMC}$ [GeV]",
    "m_h_recobb_lead": r"$m_{bb}(H_1)$ [GeV]",
    "m_h_recobb_lead_mucorr": r"$m^{\mu-\text{corr}}_{bb}(H_1)$ [GeV]",
    "m_h_recobb_sublead": r"$m_{bb}(H_2)$ [GeV]",
    "m_h_recotautau": r"$m_{H\tau\tau}^{reco}$ [GeV]",
    "m_hhh_vis": r"$m_{hhh}^{vis}$ [GeV]",
    "m_hhh_vis_LR": r"Large-Radius $m_{hhh}^{vis}$ [GeV]",

    "m_hhh_vis_dR": r"$m_{hhh}^{vis-dR}$ [GeV]",
    "m_hhh_truth": r"$m_{hhh}^{truth}$ [GeV]",
    "pT_h1": r"$p_T(H_1)$ [GeV]",
    "pT_h1_LR": r"$p_T(H_1)$ [GeV] (Large-Radius)",
    "pT_h2": r"$p_T(H_2)$ [GeV]",
    "pT_h2_LR": r"$p_T(H_2)$ [GeV] (Large-Radius)",
    "dR_h1": r"$\Delta R(H_1)$",
    "dR_h2": r"$\Delta R(H_2)$",
    "dR_tautau": r"$\Delta R(H_{\tau\tau}))$",
    "dEta_h1": r"$\Delta \eta(H_1)$",
    "dEta_h1": r"$\Delta \eta(H_2)$",
    "dEta_tautau": r"$\Delta \eta(H_{\tau\tau})$",
    "MET": r"$p_T^{miss}$ [GeV]",
    "dphi_sig_met_real_met": r"$\Delta \phi(E_T^{miss,sig}, E_T^{miss,real})$",
    "x1": r"Leading $\tau_{vis}$ momentum fraction",
    "x2": r"Sub-leading $\tau_{vis}$ momentum fraction",
    "sqrt_x1x2": r"$\sqrt{x_1 x_2}$",
    "pT_b1": r"$p_T(b_1)$ [GeV]",
    "pT_b2": r"$p_T(b_2)$ [GeV]",
    "pT_b3": r"$p_T(b_3)$ [GeV]",
    "pT_b4": r"$p_T(b_4)$ [GeV]",
    "pT_bb": r"Leading $bb$ $p_T$ [GeV]",
    "pT_tau1": r"$p_T(\tau_1)$ [GeV]",
    "pT_tau2": r"$p_T(\tau_2)$ [GeV]",
    "pT_tau1_tlv_LH": r"$p_T(\tau_1)$ [GeV]",
    "pT_tau2_tlv_LH": r"$p_T(\tau_2)$ [GeV]",

    "pt_MC_immediate_Higgs_daughters_1": r"Truth leading Hbb $p_T$ [GeV]",
    "pT_Htautau_cand": r"$p_T(H(\tau\tau))$ [GeV]",
    "eta_Htautau_cand": r"$\eta(H(\tau\tau))$",
    "eta_h1": r"$\eta(H_1)$",
    "eta_h2": r"$\eta(H_2)$",
    "deta_h1h2": r"$\Delta(\eta(H_1) - \eta(H_2))$",
    "phi_Htautau_cand": r"$\varphi(H(\tau\tau))$",
    "n_b_jets_tight": r"$n_{b}^{T}$",
    "n_b_jets_medium_tauprio": r"$n_{b}^{M}$ (OR)",
    "n_b_jets_loose": r"$n_{b}^{L}$",
    "n_tau_jets_tight": r"$n_{\tau}^{T}$",
    "n_tau_jets_medium": r"$n_{\tau}^{M}$",
    "n_tau_jets_medium_nob": r"$n_{\tau}^{M}$ (OR)",
    "n_jets_sel": "Number of reconstructed jets",
    "n_tau_jets_loose": r"$n_{\tau}^{L}$",
    "n_sel_el_0p2": r"$n_{e}^{\text{iso}}$",
    "n_el_non_iso": r"$n_{e}^{\text{all}}$",
    "n_el_pass_cut": r"$n_{e}^{\text{iso-pass}}$",
    "n_el_fail_cut": r"$n_{e}^{\text{iso-fail}}$",
    "n_sel_mu": r"$n_{\mu}^{\text{iso}}$",
    "el1_pt": r"$p_T(e_1)$ [GeV]",
    "el2_pt": r"$p_T(e_2)$ [GeV]",
    "pT_leading_taumu_fromH": r"Truth leading $p_T(\tau_{\mu})$ [GeV]",
    "pT_leading_tauel_fromH": r"Truth leading $p_T(\tau_e)$ [GeV]",

    "mu1_pt": r"$p_T(\mu_1)$ [GeV]",
    "mu2_pt": r"$p_T(\mu_2)$ [GeV]",
    "n_MC_taus": r"$n_{\tau}^{truth}$",
    "n_MC_tauhad": r"$n_{\tau-had}^{truth}$",
    "pT_MC_Higgs1": r"Truth leading Hbb $p_T$",
    "pT_MC_Higgs2": r"Truth sub-leading Hbb $p_T$",
    "pT_MC_Higgs3": r"Truth H($\tau\tau$) $p_T$",
    "pt_MC_HiggspT1": r"Truth leading Higgs $p_T$",
    "pt_MC_HiggspT2": r"Truth sub-leading Higgs $p_T$",
    "pt_MC_HiggspT3": r"Truth sub-sub-leading Higgs $p_T$",
    "eta_MC_Higgs1": r"Truth leading Hbb $\eta$",
    "eta_MC_Higgs2": r"Truth sub-leading Hbb $\eta$",
    "eta_MC_Higgs3": r"Truth H($\tau\tau$) $\eta$",
    "eta_MC_HiggspT1": r"Truth leading Higgs $\eta$",
    "eta_MC_HiggspT2": r"Truth sub-leading Higgs $\eta$",
    "eta_MC_HiggspT3": r"Truth sub-sub-leading Higgs $\eta$",
    "m_vis_1": r"$m_{\text{vis}}^1$",
    "m_vis_2": r"$m_{\text{vis}}^2$",
    "p_mis_1": r"$|p_{\text{mis}}^1|$",
    "p_mis_2": r"$|p_{\text{mis}}^2|$",
    "p_vis_1": r"$|p_{\text{mis}}^1|$",
    "p_vis_2": r"$|p_{\text{mis}}^2|$",
    "x_visE_1": r"$x^{\tau}_1$",
    "x_visE_2": r"$x^{\tau}_2$",
    "angle3D_vis_mis_tau1": r"$\theta_{3D}^1$",
    "angle3D_vis_mis_tau2": r"$\theta_{3D}^2$",
    "n_prongs_tau1": r"$n_{\text{prongs}^{\tau_1}}$",
    "n_prongs_tau2": r"$n_{\text{prongs}^{\tau_2}}$",
    "n_charged_had_truth_1": r"$n_{\text{prongs}^{\tau_1 - truth}}$",
    "n_charged_had_truth_2": r"$n_{\text{prongs}^{\tau_2 - truth}}$",
    "OS_tau": r"OS($\tau_h \tau_h$)",
    "OS_taumu": r"OS($\tau_h \tau_{\mu}$)",
    "OS_taue": r"OS($\tau_h \tau_{e}$)",
    "WlWlFilter": "WWFilter",
    "isRecoMatchedHHH_nonunique": "Reco-matched HHH",
    "isRecoMatchedHHH": "Non-unique Reco-matched HHH",
    "isRecoMatchedHHH_LR": "Reco-matched HHH [LR]",
    "pT_truth_hbb1": r"$p_T\left(H_1(bb)\right)$",
    "pT_truth_hbb2": r"$p_T\left(H_2(bb)\right)$",
    "pT_truth_htautau": r"$p_T\left(H_1(\tau\tau)\right)$",

    "isRecoMatchedHHH_LR": "Reco-matched HHH [LR]",
    "isRecoMatchedHHH_LR": "Reco-matched HHH [LR]",
    "Higgs_HT_truth": r"Truth scalar sum Higgs $p_T$",
    "Higgs_HT": r"Scalar sum Higgs $p_T$",
    "dR_truth_tautau": r"$\Delta R(H\tau\tau)$",
    "dR_truth_bb1": r"Leading Higgs $\Delta R(bb)$",
    "dR_truth_bb2": r"Sub-leading Higgs $\Delta R(bb)$",
    "m_mis_truthHadronicTaus_1": r"$m_{\mathrm{miss}}^{\tau_{1}}$ [GeV]",
    "m_mis_truthHadronicTaus_2": r"$m_{\mathrm{miss}}^{\tau_{2}}$ [GeV]",

    "m_vis_truthHadronicTaus_1": r"$m_{\mathrm{vis}}^{\tau_{1}}$ [GeV]",
    "n_neutral_truthHadronicTaus_1": r"$N_{\mathrm{neutral}}^{\tau_{1}}$",
    "n_charged_truthHadronicTaus_1": r"$N_{\mathrm{charged}}^{\tau_{1}}$",
    "pmis_truthHadronicTaus_1": r"$p_{T,\mathrm{miss}}^{\tau_{1}}$ [GeV]",
    "pvis_truthHadronicTaus_1": r"$p_{T,\mathrm{vis}}^{\tau_{1}}$ [GeV]",
    "m_vis_truthHadronicTaus_2": r"$m_{\mathrm{vis}}^{\tau_{2}}$ [GeV]",
    "n_neutral_truthHadronicTaus_2": r"$N_{\mathrm{neutral}}^{\tau_{2}}$",
    "n_charged_truthHadronicTaus_2": r"$N_{\mathrm{charged}}^{\tau_{2}}$",
    "pmis_truthHadronicTaus_2": r"$p_{T,\mathrm{miss}}^{\tau_{2}}$ [GeV]",
    "pvis_truthHadronicTaus_2": r"$p_{T,\mathrm{vis}}^{\tau_{2}}$ [GeV]",
    "MMC_unweighted_mass": r"Unweighted MMC [n($\phi$) steps = 20]",
    "MMC_unweighted_mass_40": r"Unweighted MMC [n($\phi$) steps = 40]",
    "MMC_unweighted_mass_60": r"Unweighted MMC [n($\phi$) steps = 60]",
    "MMC_unweighted_mass_80": r"Unweighted MMC [n($\phi$) steps = 80]",
    "MMC_unweighted_mass_120": r"Unweighted MMC [n($\phi$) steps = 120]",
    "MMC_mass_angular_weighted": r"$m_{\tau\tau}^{\text{MMC}}$ [Angular]",
    "MMC_mass_METScan_weighted_80_10": r"$m_{\tau\tau}^{\text{MMC}}$ [MetScan]",
    "sigma_12": r"$\sigma_{12}$",
    "sigma_13": r"$\sigma_{13}$",
    "sigma_23": r"$\sigma_{23}$",
    "sigma_x": r"$\sigma_x$",
    "sigma_y": r"$\sigma_y$",
    "n_genmatch_truth_tau1": r"$N_{\mathrm{genmatch}}^{\tau_{1}}$",
    "n_genmatch_truth_tau2": r"$N_{\mathrm{genmatch}}^{\tau_{2}}$",
    "unweighted_MMC_para_perp": r"Unweighted MMC [$\sigma_{\parallel}$]",
    "unweighted_MMC_para_perp_vispTcal": r"Unweighted $m_{\tau\tau}^{\text{MMC}}$ [GeV]",
    "weighted_MMC_para_perp_vispTcal": r"$m_{\tau\tau}^{\text{MMC}}$ [GeV]",
    "weighted_MMC_para_perp": r"Weighted MMC [$\sigma_{\parallel}$]",
    "full_mode_vispTcal": r"Fully weighted MMC (visible pT)]",

    "full_mode": r"Fully weighted MMC [$\sigma_{\parallel}$]",
    "ratioOnly_mode": r"Ratio weighted MMC [$\sigma_{\parallel}$]",
    "ratioOnly_mode_vispTcal": r"Ratio weighted MMC vispTcal",
    "angleOnly_mode": r"Angle weighted MMC [$\sigma_{\parallel}$]",

    "angleOnly_mode_vispTcal": r"Angle weighted MMC vispTcal",
    "metOnly_mode": r"MET weighted MMC [$\sigma_{\parallel}$]",
    "metOnly_mode_vispTcal": r"MET weighted MMC vispTcal",
    "metRatio_mode": r"MET + Ratio weighted MMC [$\sigma_{\parallel}$]",

    "metRatio_mode_vispTcal": r"MET + Ratio weighted MMC vispTcal",
    "metAngleOnly_mode": r"MET + Angle weighted MMC [$\sigma_{\parallel}$]",
    "metAngleOnly_mode_vispTcal": r"MET + Angle weighted MMC vispTcal",
    "recomatch_weighted_MMC_para_perp": r"Weighted reco-matched MMC [$\sigma_{\parallel}$]",
    "recomatch_unweighted_MMC_para_perp": r"Unweighted reco-matched MMC [$\sigma_{\parallel}$]",
    "MET_x": r"$p_{\text{x}}^{\text{miss}}$",
    "MET_y": r"$p_{\text{y}}^{\text{miss}}$",
    "MET": r"$p_{\text{T}}^{\text{miss}}$",
    "gen_MET_x": r"Generated $p_{\text{x}}^{\text{miss}}$",
    "gen_MET_y": r"Generated $p_{\text{y}}^{\text{miss}}$",
    "gen_MET": r"Generated $p_{\text{T}}^{\text{miss}}$",
    "d_MET_x": r"$\Delta(p_{\text{x}}^{\text{miss}}, \text{Generated} p_{\text{x}}^{\text{miss}})$",
    "d_MET_x": r"$\Delta(p_{\text{y}}^{\text{miss}}, \text{Generated} p_{\text{y}}^{\text{miss}})$",
    "d_MET": r"$\Delta(p_{\text{T}}^{\text{miss}}, \text{Generated} p_{\text{T}}^{\text{miss}})$",

    
    # bbaa variables
    "m_bb": r"$m_{bb}$ [GeV]",
    "m_hh": r"$m_{hh}$ [GeV]",
    "m_yy": r"$m_{\gamma\gamma}$ [GeV]",
    "cos_theta_yy": r"$\cos\theta^*_{\gamma\gamma}$",
    "cos_theta_yy_yybb": r"$\cos\theta^*_{\gamma\gamma} [HH]$",
    "cos_theta_bb": r"$\cos\theta^*_{bb}$",
    "min_dr_yb": r"$\min\Delta R(b\gamma)$",
    "max_dr_yb": r"$\max\Delta R(b\gamma)$",
    "dR_hh": r"$\Delta R (hh)$",
    "pT_hbb": r"$p_{\text{T}}(bb)$",
    "pT_hyy": r"$p_{\text{T}}(\gamma\gamma)$",
    "dR_yy": r"$\Delta R (\gamma\gamma)$",
    "dphi_bb": r"$\Delta\phi (bb)$",
    "dphi_yy": r"$\Delta\phi (\gamma\gamma)$",
    "deta_yy": r"$\Delta\eta (\gamma\gamma)$",
    "deta_bb": r"$\Delta\eta (bb)$"
}

process_labels: Dict[str, str] = {
    "mgp8_pp_hhh_84TeV": r"$HHH$",
    "mgp8_pp_hhh_14TeV": r"$HHH$ 14 TeV",
    "mgp8_pp_hhh_84TeV_fixcard": r"$hhh \rightarrow 4b\,2\tau$ [New Card]",
    "mgp8_pp_ttbb_4f_84TeV": r"$t\bar{t}b\bar{b}$",
    "mgp8_pp_ttbb_4f_84TeV_fakes": r"$t\bar{t}b\bar{b}$ (emutau)",
    "mgp8_pp_tth_5f_84TeV": r"$t\bar{t}H$",
    "mgp8_pp_ttz_5f_84TeV": r"$t\bar{t}Z$",
    "mgp8_pp_tttt_5f_84TeV": r"$t\bar{t}t\bar{t}$",
    "mgp8_pp_hh01j_5f_84TeV": r"$hh + j$",
    "mgp8_pp_zzz_5f_84TeV": r"$ZZZ$",
    "mgp8_pp_z0123j_4f_84TeV": r"$Z+0123j$",
    "mgp8_pp_z_4f_84TeV": r"$Z$",
    "mgp8_pp_zz012j_4f_84TeV": r"$ZZ+012j$",
    "mgp8_pp_hhjj_5f_84TeV": r"$hh + jj$ Fixed order",
    
    "pwp8_pp_hh_k3_1_k4_1_84TeV": r"$HH$",
    "mgp8_pp_h012j_5f_84TeV": r"ggF $H$",
    "mgp8_pp_tth01j_5f_84TeV": r"$t\bar{t}H$",
    "mgp8_pp_jjaa_5f_84TeV": r"$\gamma\gamma jj$",
    "mgp8_pp_vbf_h01j_5f_84TeV": r"VBF $H$"


}

process_colours: Dict[str, str] = {
    "mgp8_pp_hhh_84TeV": "black",         # signal
    "mgp8_pp_hhh_84TeV_fixcard": "blue",        
    "mgp8_pp_hhh_14TeV": "blue",        
    "pwp8_pp_hh_k3_1_k4_1_84TeV": "brown",
    "mgp8_pp_zzz_5f_84TeV": "#80CDE8",    
    "mgp8_pp_tttt_5f_84TeV": "#CD5C5C",  
    "mgp8_pp_hh01j_5f_84TeV": "#ACACAC", 
    "mgp8_pp_ttz_5f_84TeV": "#FFC000",   
    "mgp8_pp_tth_5f_84TeV": "#5499C7",   
    "mgp8_pp_ttbb_4f_84TeV": "#E67E22",   
    "mgp8_pp_ttbb_4f_84TeV_fakes": "#A688DE",   
    "mgp8_pp_z0123j_4f_84TeV":"#263472",
    "mgp8_pp_z_4f_84TeV":"#263472",
    "mgp8_pp_zz012j_4f_84TeV": "gray",
    "mgp8_pp_hhjj_5f_84TeV": "#ACACAC",
    "mgp8_pp_h_5f_84TeV":"gray",

    # signal (hh)
    "pwp8_pp_hh_k3_1_k4_1_84TeV": "#0072B2",  # blue

    # backgrounds
    "mgp8_pp_h012j_5f_84TeV":    "#D55E00",  # (orange-red)
    "mgp8_pp_tth01j_5f_84TeV":   "#CC79A7",  # reddish purple
    "mgp8_pp_jjaa_5f_84TeV":     "#E69F00",  # orange 
    "mgp8_pp_vbf_h01j_5f_84TeV":"#009E73",  # bluish green


}

channel_labels: Dict[str, str] = {
    "LepHad": r"$\tau_{\text{lep}}\tau_{\text{had}}$",
    "HadHad": r"$\tau_{\text{had}}\tau_{\text{had}}$",
    "HadHad_bb": r"$\tau_{\text{had}}\tau_{\text{had}}(bb)$",
    "HadHad_tautau": r"$\tau_{\text{had}}\tau_{\text{had}}(tautau)$",
    "HadHad_resolved": r"$\tau_{\text{had}}\tau_{\text{had}}(\text{resolved})$",
    "HadHad_resolved_dRCuts": r"$\tau_{\text{had}}\tau_{\text{had}}(\text{resolved})$ $\Delta R$ Cuts",
    "HadHad_resolved_squareCuts": r"$\tau_{\text{had}}\tau_{\text{had}}(\text{resolved})$ Square Cuts",

    "LepHad_resolved": r"$\tau_{\text{lep}}\tau_{\text{had}}(\text{resolved})$",
    "HadHad_boosted": r"$\tau_{\text{had}}\tau_{\text{had}}(boost)$",
    "HadHad_1BB": r"$\tau_{\text{had}}\tau_{\text{had}}(\text{1 bb boosted})$",
    "HadHad_2BB": r"$\tau_{\text{had}}\tau_{\text{had}}(\text{2 bb boosted})$",
    "LepHad_1BB": r"$\tau_{\text{lep}}\tau_{\text{had}}(\text{1 bb boosted})$",
    "LepHad_2BB": r"$\tau_{\text{lep}}\tau_{\text{had}}(\text{2 bb boosted})$",
    "LepHad_old": r"$\tau_{\text{lep}}\tau_{\text{had}}(\text{old})$",
    "HadHad_old": r"$\tau_{\text{had}}\tau_{\text{had}}(\text{old})$",
    "HadHad_old_dRCuts": r"$\tau_{\text{had}}\tau_{\text{had}}(\Delta R)$",
    "HadHad_old_squareCuts": r"$\tau_{\text{had}}\tau_{\text{had}}(\text{square})$",
    "TruthRecoTau": r"Truth-reco",
    "TruthRecob": r"Truth-reco",
    "TruthRecoall": r"Truth-reco",
    "HH4bMatch": r"4b Pairing",
    "Combined": "Combined",
    "Total": "Preselection",
    "HadHad_failedMMC": "Failed MMC Configurations",
    "HadHad_passMMC": "Successful MMC Configurations",
    "bbaa": r"bb$\gamma\gamma$"


}

channel_colors: Dict[str, str] = {
    "LepHad": "#859AFA",  
    "HadHad_passMMC": 'green',
    "HadHad_failedMMC": 'blue',
    "HadHad_old": "blue",
    "HadHad": "#ACACAC",
    "Total": "#040404"

}

def banner(ax: plt.Axes, comment: str = ""):
    ax.text(
        0.04, 0.96,
        r"$\mathbf{FCC\text{-}hh}$ Scenario II" "\n"
        r"$\mathit{Delphes}$ Simulation" "\n"
        r"$\sqrt{s}=84\,\mathrm{TeV}$, 30ab$^{-1}$",
        transform=ax.transAxes,
        va="top", ha="left",
        fontsize=11
    )
    ax.text(0.04, 0.80, 
        rf"{comment}",
        transform=ax.transAxes,
        va="top", ha="left",
        fontsize=11
    )

def banner_heatmaps(ax: plt.Axes, comment: str = ""):
    ax.text(
        0, 1.02,  # center above the axes
        r"$\mathbf{FCC\text{-}hh}$ $\mathit{Delphes}$ Simulation" "\n"
        r"$\sqrt{s}=84\,\mathrm{TeV}$, 30 ab$^{-1}$",
        transform=ax.transAxes,
        va="bottom", ha="left",
        fontsize=11
    )
    ax.text(1.0, 1.02, 
        rf"{comment}",
        transform=ax.transAxes,
        va="bottom", ha="right",
        fontsize=11
    )